# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "打包到pgy"
  lane :beta do
    build_app(export_method: "ad-hoc")
    pgyer(api_key: "5d5fcb91da0555c7ffb85d9f75d0a9f6", user_key: "39048c80e48840e51b0cb7cda2ae582f")
  end
end
